# -*- coding: utf-8 -*-
"""house price.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15O2Wp8TT1gJxZtARX0HNwdQYh_x8A3DK
"""

pip install pandas numpy scikit-learn matplotlib seaborn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score

from google.colab import files
uploaded = files.upload()

import pandas as pd
data = pd.read_csv("house_price_dataset.csv")
print(data.head())

# Check missing values
print(data.isnull().sum())

# Features and Target
# Features and Target
X = data.drop("price", axis=1)   # All input features
y = data["price"]                # Target variable

# Train Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LinearRegression()
model.fit(X_train, y_train)

print("Model training completed!")

y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Absolute Error:", mae)
print("R2 Score:", r2)

# Example house data (must match number of features)
sample_house = X_test.iloc[0].values.reshape(1, -1)

predicted_price = model.predict(sample_house)
print("Predicted House Price:", predicted_price[0])

plt.figure(figsize=(6,6))
plt.scatter(y_test, y_pred)
plt.xlabel("Actual Prices")
plt.ylabel("Predicted Prices")
plt.title("Actual vs Predicted House Prices")
plt.show()

